-- Ejecutar este script en Supabase SQL Editor.
-- Crea las tablas usadas por el formulario, el panel de clientes y el panel de reportes.

create table if not exists public.consultas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellido text,
  email text not null,
  motivo text not null,
  mensaje text not null,
  newsletter boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.pagos (
  id bigint generated by default as identity primary key,
  orden text,
  banco text not null,
  monto numeric(10, 2) not null,
  estado text default 'verificando',
  comprobante_nombre text,
  created_at timestamptz default now()
);

alter table public.consultas enable row level security;
alter table public.pagos enable row level security;

-- Políticas para proyecto académico/demo.
-- Permiten guardar desde el formulario público y leer desde los paneles.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'consultas' and policyname = 'Permitir insertar consultas'
  ) then
    create policy "Permitir insertar consultas"
      on public.consultas for insert
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'consultas' and policyname = 'Permitir leer consultas'
  ) then
    create policy "Permitir leer consultas"
      on public.consultas for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pagos' and policyname = 'Permitir insertar pagos'
  ) then
    create policy "Permitir insertar pagos"
      on public.pagos for insert
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pagos' and policyname = 'Permitir leer pagos'
  ) then
    create policy "Permitir leer pagos"
      on public.pagos for select
      using (true);
  end if;
end $$;
